version: '3.9'
services:
  api:
    env_file:
      - ./.env
    image: rxcrud/api:1.0
    restart: on-failure
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 5002:80
      - 5003:443
    volumes:
      - ./certificate:/app/certificate
      - ./temp-keys:/root/.aspnet/DataProtection-Keys
    environment:
      - TZ=America/Sao_Paulo
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_ConnectionStrings__DefaultConnection=Host=IP_SERVIDOR;Port=5432;Database=RXCrud;Username=postgres;Password=1234;
      - Kestrel__Certificates__Default__Password=1234
      - Kestrel__Certificates__Default__Path=/app/certificate/certificate.pfx
    networks:
      - docker_net

networks:
  docker_net: