name: rxcrud
on:
  push:
    branches: [main]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql user: "postgres"
          postgresql password: "1234"
      - name: Install Dependencies
        run: dotnet restore
      - name: Build Project
        run: dotnet build --configuration Release --no-restore
      - name: Running Unit Tests
        run: dotnet test --no-restore --verbosity normal
      - name: Generate Coverage Report
        run: |
          cd ./RXCrud.NUnitTest/
          dotnet test /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=lcov
  deploy:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          usedocker: true
          healthcheck: "https://rxcrud-api-template.herokuapp.com/HealthCheck/Check"
          checkstring: '{"message":"Aplicacao Funcionando!"}'